name: flutter_radar
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
   
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  flutter_localizations:
    sdk: flutter

  dio: ^3.0.5
  # 网络请求框架
  flutter_swiper: ^1.1.6
  # 轮播图框架
  flutter_screenutil: ^0.6.1
  # 屏幕适配框架
  flutter_easyrefresh: ^2.0.4
  # 上下拉刷新框架
  provide: ^1.0.2
  # 状态管理框架
  convert_hex: ^0.1.7
  # 进制转换框架
  fluro: ^1.5.1
  # 路由框架
  url_launcher: ^5.2.5

  package_info: ^0.4.0+10

  flutter_staggered_grid_view: ^0.3.0
  # 瀑布流框架
  shared_preferences: ^0.5.4+6
  # 轻量持久化框架
  fluttertoast: ^3.1.3
  # 提示框框架
  jpush_flutter: ^0.1.0
  # 极光推送框架
  
  date_format: ^1.0.8
  # 日期转换框架
  cached_network_image: ^2.0.0-rc
  flutter_progress_hud: 1.0.2
  badges: 1.1.0

  connectivity_wrapper: 1.0.2
  # 网络状态

  extended_image: ^0.7.1

  bot_toast: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:


  assets:
    - images/bg1.jpg
    - images/bg2.jpg
    - images/bg3.jpg
    - images/故宫-文华殿西.jpg
    - images/zhuhaijiegoutu.jpg
    - images/xianjiegoutu.jpg
    - images/zitangongxiting.jpg
    - images/zitangongdongting.jpg
    - images/zitangongzhongting.jpg
    - images/bingmayongA.png
    - images/bingmayongB.png
    - images/bingmayongC.png
    - images/bingmayongD.png
    - images/gongbiao.png
    - images/zhanlan.png
    - images/yuanjiao.png
    - images/landengzhengchang.png
    - images/landengone.png
    - images/landengtwo.png
    - images/hongdengyichang.png
    - images/shebeiguanli.png
    - images/xiugaimima.png
    - images/guanyuwomen.png
    - images/baojinggguanli.png
    - images/shezhi.png
    - images/jinru.png
    - images/beijing.jpeg
    - images/shanghai.jpeg
    - images/tianjin.jpeg
    - images/xian.jpeg
    - images/zhuhai.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
